### ISSUE TITLE
support recording system sound ！

### ISSUE THREAD

**Issue by sr79368142** [lextrack/MiniScreenRecorder#1]
mini does not support recording system sound when recording screen, I hope it can support recording system sound like simple, thank you very much for your labor! It has benefited me a lot!

**Comment by lextrack** [comment]
> mini does not support recording system sound when recording screen, I hope it can support recording system sound like simple, thank you very much for your labor! It has benefited me a lot!

If you are on Windows and only see the audio from your microphone, you need to enable Stereo Mix from the sound settings. This is described in the Known Issues section of the Readme. If you have another issue please describe it.
![714060d1-2f30-4a81-9548-56c0486297eb.png](https://github.com/user-attachments/assets/c273e1c5-7bbd-4095-80ad-bba7d5b45d37)

**Comment by sr79368142** [comment]
> > mini does not support recording system sound when recording screen, I hope it can support recording system sound like simple, thank you very much for your labor! It has benefited me a lot!
> 
> If you are on Windows and only see the audio from your microphone, you must enable Stereo Mix from the sound settings.
> 
> This is described in the **Known Issues** section of the Readme.
> 
> If you have another issue please describe it.
> 
> ![714060d1-2f30-4a81-9548-56c0486297eb.png](https://private-user-images.githubusercontent.com/42826936/374146804-c273e1c5-7bbd-4095-80ad-bba7d5b45d37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODMwODksIm5iZiI6MTcyODM4Mjc4OSwicGF0aCI6Ii80MjgyNjkzNi8zNzQxNDY4MDQtYzI3M2UxYzUtN2JiZC00MDk1LTgwYWQtYmJhN2Q1YjQ1ZDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDEwMTk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZWI3MjI4MmNmMTg4OTQxMjZjMGI2NTY2YjdmN2M4MzVlYWY2MzY2NjJkMjU5ODUwMjViZGNkN2UwODQyNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7Xo5o68oexhCW1Cb3lCEyc2ghqTlGLVsuqJWxFOxTXg)

Awesome! Perfect solution to my problem, thanks mate for your prompt reply, I hope the software gets better and better, I'll be keeping an eye on the progress of this project! I need an alternative to captura, although simple already meets my requirements, but as you stated in the project description, many people will want software with an auto-merge function. I would also like to point out a small problem, which is that mini is a bit big, 100m bigger than simple, and there is a mismatch with its name, 😄😄😄!

**Comment by sr79368142** [comment]
> > mini does not support recording system sound when recording screen, I hope it can support recording system sound like simple, thank you very much for your labor! It has benefited me a lot!
> 
> If you are on Windows and only see the audio from your microphone, you must enable Stereo Mix from the sound settings.
> 
> This is described in the **Known Issues** section of the Readme.
> 
> If you have another issue please describe it.
> 
> ![714060d1-2f30-4a81-9548-56c0486297eb.png](https://private-user-images.githubusercontent.com/42826936/374146804-c273e1c5-7bbd-4095-80ad-bba7d5b45d37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODMwODksIm5iZiI6MTcyODM4Mjc4OSwicGF0aCI6Ii80MjgyNjkzNi8zNzQxNDY4MDQtYzI3M2UxYzUtN2JiZC00MDk1LTgwYWQtYmJhN2Q1YjQ1ZDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDEwMTk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZWI3MjI4MmNmMTg4OTQxMjZjMGI2NTY2YjdmN2M4MzVlYWY2MzY2NjJkMjU5ODUwMjViZGNkN2UwODQyNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7Xo5o68oexhCW1Cb3lCEyc2ghqTlGLVsuqJWxFOxTXg)

Awesome! Perfect solution to my problem, thanks mate for your prompt reply, I hope the software gets better and better, I'll be keeping an eye on the progress of this project! I need an alternative to captura, although simple already meets my requirements, but as you stated in the project description, many people will want software with an auto-merge function. I would also like to point out a small problem, which is that mini is a bit big, 100m bigger than simple, and there is a mismatch with its name, 😄😄😄!

**Comment by sr79368142** [comment]
> > mini does not support recording system sound when recording screen, I hope it can support recording system sound like simple, thank you very much for your labor! It has benefited me a lot!
> 
> If you are on Windows and only see the audio from your microphone, you must enable Stereo Mix from the sound settings.
> 
> This is described in the **Known Issues** section of the Readme.
> 
> If you have another issue please describe it.
> 
> ![714060d1-2f30-4a81-9548-56c0486297eb.png](https://private-user-images.githubusercontent.com/42826936/374146804-c273e1c5-7bbd-4095-80ad-bba7d5b45d37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODMwODksIm5iZiI6MTcyODM4Mjc4OSwicGF0aCI6Ii80MjgyNjkzNi8zNzQxNDY4MDQtYzI3M2UxYzUtN2JiZC00MDk1LTgwYWQtYmJhN2Q1YjQ1ZDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDEwMTk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZWI3MjI4MmNmMTg4OTQxMjZjMGI2NTY2YjdmN2M4MzVlYWY2MzY2NjJkMjU5ODUwMjViZGNkN2UwODQyNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7Xo5o68oexhCW1Cb3lCEyc2ghqTlGLVsuqJWxFOxTXg)

Awesome! Perfect solution to my problem, thanks mate for your prompt reply, I hope the software gets better and better, I'll be keeping an eye on the progress of this project! I need an alternative to captura, although simple already meets my requirements, but as you stated in the project description, many people will want software with an auto-merge function. I would also like to point out a small problem, which is that mini is a bit big, 100m bigger than simple, and there is a mismatch with its name, 😄😄😄!
